# Generated by Django 3.2 on 2021-05-01 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_alter_pizza_pizza_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='pizza_type',
        ),
    ]
